### ISSUE TITLE
Do not work with valgrind 3.21

### ISSUE THREAD

**Issue by Fi3** [bheisler/iai#36]
I'm using fedora 38 and when I install valgrind i get the 3.21 version.
Iai seem to not work with it, if I run the example in the README I get:
```
thread 'main' panicked at 'no entry found for key', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/iai-0.1.1/src/lib.rs:163:40
```
If I print events at line 160 of lib.rs I get: `Events: {"Ir": 442824}`

Downgrading to valgrind 3.18 solve the issue

**Comment by Oppen** [comment]
I made a quick fork for those who can't migrate to `iai-callgrind` which is more actively maintained.
You can override the dep to point to the fixed version:
```toml
[patch.crates-io]
iai = { git = "https://github.com/lambdaclass/iai", branch = "fix/valgrind-forward-compatibility" }
```

What the fix does is add explicitly the `--cache-sim=yes` argument for cachegrind, since from version 3.21 and later it defaults to `--cache-sim=no`, so the expected events are not emitted.
